/**
 * Signing half of the `sig1` service credential, for the homestead.
 *
 * The verifying half lives in `@open-inspect/shared` and is the owner of this
 * grammar. This is a second implementation of it, which the codebase otherwise
 * avoids — the reason is packaging, not preference: `@open-inspect/shared` is
 * compiled with bundler module resolution and emits extensionless directory
 * imports, so it resolves under esbuild and Next but not under plain Node,
 * which is what the homestead runs on.
 *
 * A second implementation is only safe if something proves the two agree, so
 * this one is pinned to `packages/shared/test-fixtures/service-auth-vectors.json`
 * — the same golden vectors that pin the verifier, generated by an independent
 * Python reference. `service-signature.test.ts` also signs with this module and
 * verifies with shared's verifier, so a drift in either direction fails a test
 * rather than an authentication.
 *
 * Any change to the canonical layout requires a new format tag (`sig2`) in both
 * places, never an edit here.
 */

export const SERVICE_HEADER = "X-OpenOutposts-Service";
export const SERVICE_SIGNATURE_HEADER = "X-OpenOutposts-Service-Signature";
export const ACTOR_HEADER = "X-OpenOutposts-Actor";
const SIG1_PREFIX = "sig1";

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function computeHmacHex(data: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(data));
  return bytesToHex(new Uint8Array(signature));
}

export async function sha256Hex(data: Uint8Array | string): Promise<string> {
  const bytes = typeof data === "string" ? new TextEncoder().encode(data) : data;
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return bytesToHex(new Uint8Array(digest));
}

/**
 * Byte-wise comparison, not UTF-16. `String.prototype.sort` orders by code
 * unit, which puts astral characters before U+E000..U+FFFF; the reference
 * implementation orders by UTF-8 bytes.
 */
function compareUtf8Bytes(a: string, b: string): number {
  const left = new TextEncoder().encode(a);
  const right = new TextEncoder().encode(b);
  const shared = Math.min(left.length, right.length);
  for (let i = 0; i < shared; i++) {
    if (left[i] !== right[i]) return left[i] - right[i];
  }
  return left.length - right.length;
}

export function canonicalizeQuery(search: string): string {
  const params = new URLSearchParams(search);
  const entries = Array.from(params.entries());
  entries.sort((a, b) => compareUtf8Bytes(`${a[0]}\0${a[1]}`, `${b[0]}\0${b[1]}`));
  return entries
    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
    .join("&");
}

/** The exact byte layout signed by `sig1`. Every field is newline-delimited. */
export function buildCanonicalRequestString(p: {
  service: string;
  timestampMs: number;
  nonce: string;
  method: string;
  pathname: string;
  canonicalQuery: string;
  bodySha256Hex: string;
  actor: string;
}): string {
  return (
    `${SIG1_PREFIX}\n${p.service}\n${p.timestampMs}\n${p.nonce}\n` +
    `${p.method.toUpperCase()}\n${p.pathname}\n${p.canonicalQuery}\n` +
    `${p.bodySha256Hex}\n${p.actor}`
  );
}

function generateNonce(): string {
  const bytes = new Uint8Array(8);
  crypto.getRandomValues(bytes);
  return bytesToHex(bytes);
}

/**
 * Build the sig1 headers for one outbound request.
 *
 * The signature covers the method, path, canonical query and body hash, so a
 * captured header authorizes exactly the request it was made for and nothing
 * else. The control plane additionally spends the nonce, so it authorizes that
 * request once.
 */
export async function buildServiceAuthHeaders(p: {
  service: string;
  secret: string;
  method: string;
  url: string;
  body?: Uint8Array | string;
  actor?: string;
  /** Test seam. Production callers leave these to the clock and the CSPRNG. */
  timestampMs?: number;
  nonce?: string;
}): Promise<Record<string, string>> {
  const timestampMs = p.timestampMs ?? Date.now();
  const nonce = p.nonce ?? generateNonce();
  const actor = p.actor ?? "";
  const parsed = new URL(p.url);
  const bodySha256Hex = await sha256Hex(p.body ?? "");

  const signatureHex = await computeHmacHex(
    buildCanonicalRequestString({
      service: p.service,
      timestampMs,
      nonce,
      method: p.method,
      pathname: parsed.pathname,
      canonicalQuery: canonicalizeQuery(parsed.search),
      bodySha256Hex,
      actor,
    }),
    p.secret
  );

  const headers: Record<string, string> = {
    [SERVICE_HEADER]: p.service,
    [SERVICE_SIGNATURE_HEADER]: `${SIG1_PREFIX}.${timestampMs}.${nonce}.${signatureHex}`,
  };
  if (actor !== "") headers[ACTOR_HEADER] = actor;
  return headers;
}
