/**
 * Modal instance API client.
 *
 * RETAINED FOR FLEET-MEMBER PROVISIONING. Modal no longer hosts an agent: the
 * agent runs centrally and execution happens on a machine the user owns. What
 * survives here is the authenticated transport and the instance-creation call,
 * which the (not yet built) fleet-member creator will use with the *user's own*
 * Modal credential to stand up a machine running the outpost worker.
 *
 * Nothing in the control plane constructs this client today. The snapshot,
 * restore and image-build calls went with the in-sandbox runtime.
 */

import { generateInternalToken } from "@open-inspect/shared";
import { z } from "zod";
import { createLogger } from "../logger";
import type { CorrelationContext } from "../logger";
import type { SessionRepositoryInfo } from "./provider";

const log = createLogger("modal-client");

// Modal app name. Must match terraform modal.tf app_name and
// the deployed Modal application.
const MODAL_APP_NAME = "openoutposts";

// Modal's default environment name; unrelated to the git branch named "main".
const DEFAULT_MODAL_ENVIRONMENT = "main";

const modalErrorResponseSchema = z.object({
  success: z.literal(false),
  error: z.string().optional(),
});

const createSandboxModalResponseSchema = z.discriminatedUnion("success", [
  z.object({
    success: z.literal(true),
    data: z.object({
      sandbox_id: z.string(),
      modal_object_id: z.string().nullable().optional(),
      status: z.string(),
      created_at: z.number(),
    }),
  }),
  modalErrorResponseSchema,
]);

function parseModalApiResponse<T>(schema: z.ZodType<T>, body: unknown): T {
  const result = schema.safeParse(body);
  if (!result.success) {
    throw new Error("Modal API error: Invalid response");
  }
  return result.data;
}

/**
 * Build the Modal endpoint workspace slug from the raw workspace and environment web suffix.
 */
export function buildModalWorkspaceSlug(workspace: string, environmentWebSuffix = ""): string {
  return environmentWebSuffix === "" ? workspace : `${workspace}-${environmentWebSuffix}`;
}

/**
 * Construct the Modal base URL from workspace and environment web suffix.
 */
function getModalBaseUrl(workspace: string, environmentWebSuffix?: string): string {
  return `https://${buildModalWorkspaceSlug(workspace, environmentWebSuffix)}--${MODAL_APP_NAME}`;
}

/**
 * Build a Modal dashboard link for a sandbox object.
 */
export function buildModalSandboxDashboardUrl(params: {
  workspace: string | undefined;
  // Modal workspace environment (unrelated to the Environment entity); named
  // modalEnvironment to keep the term unambiguous (design §7.1).
  modalEnvironment?: string | undefined;
  providerObjectId: string | null | undefined;
}): string | null {
  if (!params.workspace || !params.providerObjectId) return null;
  const workspace = encodeURIComponent(params.workspace);
  const modalEnvironment = encodeURIComponent(params.modalEnvironment || DEFAULT_MODAL_ENVIRONMENT);
  const providerObjectId = encodeURIComponent(params.providerObjectId);
  return `https://modal.com/apps/${workspace}/${modalEnvironment}/deployed/${MODAL_APP_NAME}?activeTab=sandboxes&sandboxId=${providerObjectId}`;
}

export interface CreateSandboxRequest {
  sessionId: string;
  /** Expected instance ID (generated by control plane) */
  sandboxId?: string;
  repoOwner: string | null;
  repoName: string | null;
  controlPlaneUrl: string;
  sandboxAuthToken: string;
  provider?: string;
  model?: string;
  timeoutSeconds?: number;
  branch?: string | null;
  repositories?: SessionRepositoryInfo[];
}

export interface CreateSandboxResponse {
  sandboxId: string;
  /** Modal's internal object ID */
  modalObjectId?: string;
  status: string;
  createdAt: number;
}

/**
 * Error thrown by ModalClient when the Modal API returns a non-OK HTTP status.
 * Carries the numeric status code so callers can classify without string parsing.
 */
export class ModalApiError extends Error {
  constructor(
    message: string,
    public readonly status: number
  ) {
    super(message);
    this.name = "ModalApiError";
  }
}

/**
 * Modal sandbox API client.
 *
 * Requires MODAL_API_SECRET for authentication and MODAL_WORKSPACE for URL construction.
 */
export class ModalClient {
  private createSandboxUrl: string;
  private secret: string;

  constructor(secret: string, workspace: string, environmentWebSuffix?: string) {
    if (!secret) {
      throw new Error("ModalClient requires MODAL_API_SECRET for authentication");
    }
    if (!workspace) {
      throw new Error("ModalClient requires MODAL_WORKSPACE for URL construction");
    }
    this.secret = secret;
    const baseUrl = getModalBaseUrl(workspace, environmentWebSuffix);
    this.createSandboxUrl = `${baseUrl}-api-create-sandbox.modal.run`;
  }

  /**
   * Generate authentication headers for POST/PUT requests (includes Content-Type).
   */
  private async getPostHeaders(correlation?: CorrelationContext): Promise<Record<string, string>> {
    const token = await generateInternalToken(this.secret);
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    };
    if (correlation?.trace_id) headers["x-trace-id"] = correlation.trace_id;
    if (correlation?.request_id) headers["x-request-id"] = correlation.request_id;
    if (correlation?.session_id) headers["x-session-id"] = correlation.session_id;
    if (correlation?.sandbox_id) headers["x-sandbox-id"] = correlation.sandbox_id;
    return headers;
  }

  /**
   * Create a new sandbox for a session.
   */
  async createSandbox(
    request: CreateSandboxRequest,
    correlation?: CorrelationContext
  ): Promise<CreateSandboxResponse> {
    const startTime = Date.now();
    const endpoint = "createSandbox";
    let httpStatus: number | undefined;
    let outcome: "success" | "error" = "error";

    try {
      const headers = await this.getPostHeaders(correlation);
      const response = await fetch(this.createSandboxUrl, {
        method: "POST",
        headers,
        body: JSON.stringify({
          session_id: request.sessionId,
          sandbox_id: request.sandboxId || null, // Use control-plane-generated ID
          repo_owner: request.repoOwner,
          repo_name: request.repoName,
          control_plane_url: request.controlPlaneUrl,
          sandbox_auth_token: request.sandboxAuthToken,
          provider: request.provider || "anthropic",
          model: request.model || "claude-sonnet-4-6",
          timeout_seconds: request.timeoutSeconds || null,
          branch: request.branch || null,
          repositories: request.repositories?.length
            ? request.repositories.map((repository) => ({
                repo_owner: repository.repoOwner,
                repo_name: repository.repoName,
                branch: repository.baseBranch,
                base_sha: repository.baseSha ?? null,
              }))
            : null,
        }),
      });

      httpStatus = response.status;

      if (!response.ok) {
        const text = await response.text();
        throw new ModalApiError(`Modal API error: ${response.status} ${text}`, response.status);
      }

      const result = parseModalApiResponse(createSandboxModalResponseSchema, await response.json());

      if (!result.success) {
        throw new Error(`Modal API error: ${result.error || "Unknown error"}`);
      }

      outcome = "success";
      return {
        sandboxId: result.data.sandbox_id,
        modalObjectId: result.data.modal_object_id ?? undefined,
        status: result.data.status,
        createdAt: result.data.created_at,
      };
    } finally {
      log.info("modal.request", {
        event: "modal.request",
        endpoint,
        session_id: request.sessionId,
        sandbox_id: request.sandboxId,
        trace_id: correlation?.trace_id,
        request_id: correlation?.request_id,
        http_status: httpStatus,
        duration_ms: Date.now() - startTime,
        outcome,
      });
    }
  }
}

/**
 * Create a new Modal client instance.
 *
 * This is a simple factory function that creates a new client each time.
 * The caller is responsible for managing the client lifecycle.
 *
 * @param secret - The MODAL_API_SECRET for authentication
 * @param workspace - The Modal workspace name
 * @param environmentWebSuffix - The Modal environment web suffix used in endpoint URLs
 * @returns A new ModalClient instance
 * @throws Error if secret or workspace is not provided
 */
export function createModalClient(
  secret: string,
  workspace: string,
  environmentWebSuffix?: string
): ModalClient {
  if (!secret) {
    throw new Error("MODAL_API_SECRET is required to create ModalClient");
  }
  if (!workspace) {
    throw new Error("MODAL_WORKSPACE is required to create ModalClient");
  }
  return new ModalClient(secret, workspace, environmentWebSuffix);
}
