/**
 * Execution backend interface.
 *
 * The agent no longer runs inside a provisioned sandbox: it runs centrally and
 * every file and shell operation executes on an outpost the user owns. What
 * survives here is the narrow contract the session lifecycle needs to hand a
 * session to an execution backend — create, and nothing else.
 *
 * Snapshot, restore, resume and provider-side stop are gone with the in-sandbox
 * runtime: an outpost is a durable machine whose filesystem the product does
 * not own, so there is nothing to snapshot and nothing to resume.
 */

import type { SandboxSettings } from "@open-inspect/shared";
import type { CorrelationContext } from "../logger";

/** Default sandbox lifetime in seconds (2 hours). */
export const DEFAULT_SANDBOX_TIMEOUT_SECONDS = 7200;

/**
 * One member repository of a session, in position order (first = primary).
 */
export interface SessionRepositoryInfo {
  repoOwner: string;
  repoName: string;
  /** Base branch to clone (resolved at session create; never null). */
  baseBranch: string;
  /** Immutable session-start commit used by the Changes capture protocol. */
  baseSha?: string | null;
}

/**
 * Configuration for handing a session to an execution backend.
 */
export interface CreateSandboxConfig {
  /** Session ID for WebSocket routing */
  sessionId: string;
  /** Expected sandbox ID (generated by control plane) */
  sandboxId: string;
  /** Repository owner */
  repoOwner: string | null;
  /** Repository name */
  repoName: string | null;
  /** Control plane URL for sandbox callbacks */
  controlPlaneUrl: string;
  /** Authentication token for sandbox */
  sandboxAuthToken: string;
  /**
   * Session-scoped credential for the model-credential broker and nothing
   * else. Delivered to whatever runs the harness.
   */
  credentialFetchToken: string;
  /** LLM provider (e.g., "anthropic") */
  provider: string;
  /** LLM model (e.g., "claude-sonnet-4-5") */
  model: string;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /** Git branch to work on (defaults to repo's default branch) */
  branch?: string | null;
  /** Sandbox settings resolved from integration settings */
  sandboxSettings?: SandboxSettings;
  /**
   * Pinned outpost execution target for the session. Null falls back to the
   * deployment's default target.
   */
  outpostId?: string | null;
  /**
   * Ordered member list for multi-repo sessions. Only set when the session
   * has more than one member — single-repo sessions keep the scalar
   * repoOwner/repoName/branch wire form. Working-branch names are not part of
   * this config: they are derived lazily at PR-creation time
   * (pull-request-service) and travel in per-repo push specs.
   */
  repositories?: SessionRepositoryInfo[];
}

/**
 * Result of handing a session to an execution backend.
 */
export interface CreateSandboxResult {
  /** The sandbox ID (should match expected ID from config) */
  sandboxId: string;
  /** Initial sandbox status */
  status: string;
  /** Creation timestamp */
  createdAt: number;
}

/**
 * Error classification for circuit breaker decisions.
 *
 * Only permanent failures should count toward the circuit breaker threshold.
 * Transient failures (network issues, timeouts) are logged but don't trip the breaker.
 *
 * Transient errors (do NOT count toward circuit breaker):
 * - ETIMEDOUT, ECONNRESET, ECONNREFUSED
 * - HTTP 502, 503, 504 (Bad Gateway, Service Unavailable, Gateway Timeout)
 * - "fetch failed" / network errors
 *
 * Permanent errors (DO count toward circuit breaker):
 * - HTTP 400, 401, 403, 422 (Bad Request, Unauthorized, Forbidden, Unprocessable)
 * - Invalid configuration
 * - Resource quota exceeded
 */
export type SandboxErrorType = "transient" | "permanent";

/**
 * Custom error class for sandbox provider operations.
 *
 * Includes error type classification for circuit breaker handling.
 * The circuit breaker only counts permanent errors toward its threshold.
 */
export class SandboxProviderError extends Error {
  constructor(
    message: string,
    public readonly errorType: SandboxErrorType,
    public readonly cause?: Error
  ) {
    super(message);
    this.name = "SandboxProviderError";
    // Maintain proper stack trace in V8 environments
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, SandboxProviderError);
    }
  }

  /**
   * Check if an HTTP status code indicates a transient error.
   */
  static isTransientStatus(status: number): boolean {
    return status === 502 || status === 503 || status === 504;
  }

  /**
   * Check if an error is likely a transient network error.
   */
  static isTransientNetworkError(error: unknown): boolean {
    if (error instanceof Error) {
      const message = error.message.toLowerCase();
      return (
        message.includes("fetch failed") ||
        message.includes("etimedout") ||
        message.includes("econnreset") ||
        message.includes("econnrefused") ||
        message.includes("network") ||
        message.includes("timeout")
      );
    }
    return false;
  }

  /**
   * Create a SandboxProviderError from a fetch error or HTTP response.
   */
  static fromFetchError(message: string, error: unknown, status?: number): SandboxProviderError {
    // Classify based on HTTP status if available
    if (status !== undefined) {
      const errorType = SandboxProviderError.isTransientStatus(status) ? "transient" : "permanent";
      return new SandboxProviderError(
        message,
        errorType,
        error instanceof Error ? error : undefined
      );
    }

    // Classify based on error type
    const errorType = SandboxProviderError.isTransientNetworkError(error)
      ? "transient"
      : "permanent";
    return new SandboxProviderError(message, errorType, error instanceof Error ? error : undefined);
  }
}

/**
 * Execution backend interface.
 *
 * Error handling:
 * - Methods should throw SandboxProviderError with appropriate errorType
 * - "transient" errors (network issues) don't count toward circuit breaker
 * - "permanent" errors (config issues) do count toward circuit breaker
 */
export interface SandboxProvider {
  /** Provider name for logging and debugging */
  readonly name: string;

  /**
   * Hand a session to the execution backend.
   *
   * @param config - Session configuration
   * @returns Creation result with sandbox ID and status
   * @throws SandboxProviderError with errorType for circuit breaker handling
   */
  createSandbox(config: CreateSandboxConfig): Promise<CreateSandboxResult>;
}
